### ISSUE TITLE
Screenshot font?

### ISSUE THREAD

**Issue by ycanales** [EryouHao/brackets-light-pro#5]
It would be cool if you add it in the description. Looks like Fantasque Sans Mono?

**Comment by EryouHao** [comment]
Yes, you are right. I have already added it to README. Thank you for your feedback.

**Comment by waldyrious** [comment]
> Yes, you are right. I have already added it to README. Thank you for your feedback.

For reference, that was done in 8a0a391. @EryouHao did you intentionally leave this issue open?
