### ISSUE TITLE
Change font color of suggestions

### ISSUE THREAD

**Issue by albtam** [EryouHao/brackets-light-pro#9]
With the new VS Code 1.57 update, the selected suggestion is not visible anymore(blue on blue). It would useful to change the color of the font.

![image](https://user-images.githubusercontent.com/30054037/121922803-9403b400-cd3a-11eb-84fb-b7e3574ba8f1.png)

**Comment by 0xbdm0101** [comment]
我也有此问题

**Comment by albtam** [comment]
Thanks for solving that issue
